import Head from 'next/head'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import Categories from './components/Categories'
import Meridian from './components/Meridian'
import Carousel from './components/Carousel'
import UAHOVR from './components/UAHOVR'
import Extras from './components/Extras'
import Footer from './components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Under Armour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Categories />
      <Meridian />
      <Carousel />
      <UAHOVR />
      <Extras />
      <Footer />
    </div>
  )
}
